project:
  type: book
  output-dir: docs

book:
  title: "Telling Stories with Data"
  author: "Rohan Alexander"
  date: "19 July 2022"
  search: true
  cover-image: figures/tellingstorieswithdatapainting.png
  repo-url: https://github.com/RohanAlexander/telling_stories/
  repo-actions: [edit]
  site-url: https://tellingstorieswithdata.com
  callout-appearance: simple
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - 00-author.qmd
    - part: "Foundations"  
      chapters: 
        - 01-introduction.qmd
        - 02-drinking_from_a_fire_hose.qmd
        - 03-r_essentials.qmd
        - 04-workflow.qmd
    - part: "Communication"  
      chapters: 
        - 05-on_writing.qmd
        - 06-static_communication.qmd
        - 07-interactive_communication.qmd
    - part: "Acquisition"  
      chapters: 
        - 08-farm.qmd
        - 09-gather.qmd
        - 10-hunt.qmd
    - part: "Preparation"  
      chapters: 
        - 11-clean_and_prepare.qmd
        - 12-store_and_share.qmd
    - part: "Modelling"  
      chapters: 
        - 13-eda.qmd
        - 14-ijalm.qmd
        - 15-causality_from_obs.qmd
        - 16-mrp.qmd
        - 17-text.qmd
        - 20-concluding.qmd
  appendices:
    - 22-datasets.qmd
    - 23-rmarkdown.qmd
    - 24-assessment.qmd
    - 25-datasheet.qmd
    - 98-cocktails.qmd
    - 99-references.qmd
  engine: knitr
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: krantz
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    keep-tex: true
